### PR TITLE
Migration to RestSharp 107, added multiple features/optimizations

### PR DESCRIPTION
**Pull request by TobiKr**
Hi!

I added multiple features:
- Migration from RestSharp 106 to RestSharp 107 (as 107 is required in one of my other projects that include UniFiSharp)
- Added timeout setting
- Added parameter descriptions in hotspot class
- added HotspotVoucherTerminate Method
- added ClientUnauthorize Method

I would really like to know if you are happy with my additions or if you have any improvements.

Thanks
Tobias

### CODE REVIEW

**Comment by anthturner** [comment]
@TobiKr Looks like the build is failing; can you look into this? (If it's an issue with the Action and you don't feel comfortable adjusting it, LMK and I can poke at it if you give me the new requirements)

**Comment by TobiKr** [comment]
Hi @anthturner, thanks for the info. RestSharp 107 does not support .NET Core 2.1 (https://stackoverflow.com/questions/71255156/restsharp-error-in-azure-pipeline-restresponsebase-statuscode-is-not-supporte)
Would it be ok to switch the pipeline to .NET Core 3.1? 2.1 is already End of Support and 3.1 will be supported until 12/2022.

**Comment by anthturner** [comment]
Yeah, I expect this to bite us again in the future. We can increment this to 3.1 and just make a note in the README indicating an end of support for UniFiSharp on 2.1 starting with the next NuGet release.

**Comment by anthturner** [comment]
@TobiKr I poked around a bit, can we set the new target to `netstandard2.1` to maximize compatibility? If you could make that change to the `.csproj` file as a part of this PR, I'd appreciate it. Let's also bump version to 1.5.0 and I'll make a note on next release that we're dropping `netstandard2.0` support

**Comment by TobiKr** [comment]
@anthturner sorry for the delay, do you still want me to update the version to 1.5.0? netstandard2.1 does seem to work as well :-)

**Comment by anthturner** [comment]
Nah. I incremented it a minor version instead; there is another contributor planning on adding support for other UniFi-branded devices which will make the API surface change namespaces slightly, so I'll make that the next "major" iteration.

Thanks again for the contributions! 🙂

**Pull request merged**
